### ISSUE TITLE
Different behaviour for prebuilt and selfbuilt images

### ISSUE THREAD

**Issue by Laspav** [bitnami/bitnami-docker-drupal-nginx#14]
### Name and Version

bitnami/bitnami-docker-drupal-nginx:9

### What steps will reproduce the bug?

Dockerfile for succesful test:
```
FROM bitnami/drupal-nginx:9
RUN rm -rf /opt/bitnami/drupal
```
This finishes without issues

Clone the project and build the image yourself using the Dockerfile provided, create Dockerfile containing the newly created image:
```
FROM bitnami-drupal-selfmade
RUN rm -rf /opt/bitnami/drupal
```
This fails with a permission denied

### What is the expected behavior?

Expect same behaviour from both images, no changes have been made

### What do you see instead?

Using selfmade image:
```
> [2/2] RUN rm -rf /opt/bitnami/drupal:
#5 1.773 rm: cannot remove '/opt/bitnami/drupal': Permission denied
```

### Additional information

I wanted to extend the image to fit my purposes, but found out that images I build myself behave differently than using the prebuilt images. I included a very simplified test to show what happens. How are prebuilt images different compared to selfmade using the Dockerfile provided in 9/debian-11?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-drupal-nginx#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
