### ISSUE TITLE
Mounting the real folder project

### ISSUE THREAD

**Issue by 4goodapp** [bitnami/bitnami-docker-drupal-nginx#7]
In the container, the Drupal project is located in /opt/bitnami/drupal/ instead of /bitnami/drupal/ and mounting as volume make the conutainer exit:

**Edit post: correcting the path** 

```
volumes:
    - './drupal-site-folder:/opt/bitnami/drupal'
```

**Comment by marcosbc** [comment]
@4goodapp Could you share your use case? The Bitnami container for Drupal currently works by persisting the directories below:

- sites
- themes
- modules
- profiles

If you are not performing any change outside of those folders, you could perform these steps:

- Deploy Drupal with an empty drupal-site-folder:

        volumes:
            - './drupal-site-folder:/bitnami/drupal'

- Stop the container

- Update the contents in `drupal-site-folder` with what you want, i.e. by copying the entire directory (note that only `sites`, `themes`, `modules` and `profiles` directories will be taken into account).

- Start the container again.

If you have any reason for mounting the rest of directories, we would love to hear more on it.

**Comment by 4goodapp** [comment]
@marcosbc I use the bitnami images mostly for developement so because of that, I sometimes have the need of the other folder than the ones present in` /bitnami/drupal`.

**Comment by 4goodapp** [comment]
@marcosbc
Hello,
So is there something that can be done about this?

**Comment by marcosbc** [comment]
@4goodapp The only way that occurs me is for you to build a custom Docker image with the change below to the Dockerfile:

```
diff --git a/8/debian-10/Dockerfile b/8/debian-10/Dockerfile
index 3414e6c..db67c65 100644
--- a/8/debian-10/Dockerfile
+++ b/8/debian-10/Dockerfile
@@ -48,3 +48,5 @@ EXPOSE 80 443

 ENTRYPOINT [ "/app-entrypoint.sh" ]
 CMD [ "/run.sh" ]
+
+RUN sed -i 's/\$app\.dataToPersist/[$app.installdir]/' /root/.nami/components/com.bitnami.drupal/main.js
```

It might seem a bit obscure, but unfortunately our Docker image doesn't support your use case (yet).

In the future, when we move this container image to use Bash logic instead of Nami, changing directories to persist will be much easier. However, there isn't an ETA for when that will happen yet.
